#!/usr/bin/env node
/**
 * Post-processor: transforms k6 evidence JSON into
 * PROOFS/<SHA>/<ROW>/<seat>/k6-run-<timestamp>/ artifacts.
 *
 * Consumes ONLY redacted_events (allowlist-filtered). Refuses to write
 * if evidence contains raw unredacted 'events' field without redacted_events.
 *
 * Usage:
 *   node tools/k6-proofs/scripts/evidence-writer.mjs \
 *     --input /tmp/r-cd-1-output.txt \
 *     --row R-CD-1 \
 *     --seat ronan-dgx \
 *     --sha <40-char-hex>
 *
 * Writes:
 *   PROOFS/<sha>/<row>/<seat>/k6-run-<timestamp>/
 *     ├── EVIDENCE.md
 *     ├── k6-summary.json
 *     ├── gateway-events.ndjson  (redacted only)
 *     └── row-result.json
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

function parseArgs(argv) {
  const out = {};
  for (let i = 2; i < argv.length; i += 1) {
    const arg = argv[i];
    if (!arg.startsWith('--')) throw new Error(`unexpected argument: ${arg}`);
    const key = arg.slice(2);
    const value = argv[i + 1];
    if (!value || value.startsWith('--')) throw new Error(`missing value for --${key}`);
    out[key] = value;
    i += 1;
  }
  return out;
}

function stamp() {
  return new Date().toISOString().replace(/[-:]/g, '').replace(/\.\d{3}Z$/, 'Z');
}

function usage() {
  console.error(`Usage: node evidence-writer.mjs --input <k6-output> --row <ROW> --seat <SEAT> --sha <SHA>`);
  process.exit(2);
}

// --- Main ---
const args = parseArgs(process.argv);
if (!args.input || !args.row || !args.seat || !args.sha) usage();

// Validate SHA is 40-char hex
if (!/^[0-9a-f]{40}$/.test(args.sha)) {
  console.error(`ERROR: --sha must be a 40-character hex string (got: "${args.sha}")`);
  process.exit(1);
}

const raw = readFileSync(args.input, 'utf-8');

// Extract the evidence JSON block from k6 console output
const evidenceMatch = raw.match(/--- .* EVIDENCE SUMMARY ---\n([\s\S]*?)\n--- END EVIDENCE ---/);
if (!evidenceMatch) {
  console.error('ERROR: Could not find evidence summary block in k6 output');
  process.exit(1);
}

const evidence = JSON.parse(evidenceMatch[1]);

// --- REDACTION BOUNDARY ---
// Refuse to write if evidence has raw 'events' but no 'redacted_events'
if (evidence.events && !evidence.redacted_events) {
  console.error('ERROR: Evidence contains raw unredacted "events" field.');
  console.error('Public artifacts require "redacted_events" (allowlist-filtered).');
  console.error('Fix the scenario to use redactEvent() and store in redacted_events.');
  process.exit(1);
}

const events = evidence.redacted_events || [];

// Build output directory
const runId = `k6-run-${stamp()}`;
const outDir = join('PROOFS', args.sha, args.row, args.seat, runId);
mkdirSync(join(outDir, 'artifacts'), { recursive: true });

// Write k6-summary.json (evidence without raw events)
const summary = { ...evidence };
delete summary.redacted_events; // events go to ndjson, not summary
writeFileSync(join(outDir, 'k6-summary.json'), JSON.stringify(summary, null, 2) + '\n');

// Write gateway-events.ndjson (redacted only)
if (events.length > 0) {
  const ndjson = events.map((e) => JSON.stringify(e)).join('\n') + '\n';
  writeFileSync(join(outDir, 'gateway-events.ndjson'), ndjson);
}

// Determine verdict
const verdict = evidence.tool_accepted || evidence.prompt_sent
  ? (evidence.task_created || evidence.child_spawned ? 'PASS-candidate' : 'PARTIAL-candidate')
  : 'FAIL-candidate';

// Write row-result.json
const result = {
  schema: 'openclaw.k6.proof-row-result.v1',
  runId,
  generatedAt: new Date().toISOString(),
  rowId: args.row,
  candidateSha: args.sha,
  seat: args.seat,
  outcome: verdict,
  candidateOnly: true,
  foldRequiresReview: true,
};
writeFileSync(join(outDir, 'row-result.json'), JSON.stringify(result, null, 2) + '\n');

// Generate EVIDENCE.md
const md = `# ${args.row} — ${args.seat} — ${verdict}

> Generated by \`tools/k6-proofs/scripts/evidence-writer.mjs\`.
> This is **candidate output**, not a folded proof verdict.
> Human review is required before copying into canonical \`EVIDENCE.md\` or manifests.

## Row

- Row: \`${args.row}\`
- Candidate SHA: \`${args.sha}\`
- Seat: \`${args.seat}\`
- Run ID: \`${runId}\`
- Generated: ${result.generatedAt}

## Candidate outcome

**${verdict}**

## Evidence receipts

| Check | Result |
|-------|--------|
| Tool/prompt accepted | ${evidence.tool_accepted || evidence.prompt_sent ? '✓' : '✗'} |
| Task/child created | ${evidence.task_created || evidence.child_spawned ? '✓' : '✗'} |
| Parent return observed | ${evidence.parent_return ? '✓' : '✗'} |
| Nonce | \`${evidence.nonce || 'N/A'}\` |
| Manifest loaded | ${evidence.manifest_loaded ? '✓' : '✗ (defaults used)'} |

## Artifacts

- \`k6-summary.json\` — structured evidence (no raw events)
- \`gateway-events.ndjson\` — redacted WS frames (${events.length} captured)
- \`row-result.json\` — normalized outcome
- \`artifacts/\` — optional copied receipts (Tempo trace, logs)

## Redaction boundary

All events in \`gateway-events.ndjson\` passed through the allowlist redaction filter.
Only structural fields (type, method, IDs, timing, status) are preserved.
No tokens, secrets, prompt bodies, or user content in public artifacts.

## Review checklist

- [ ] No secrets in any artifact
- [ ] Required receipts present and byte-readable
- [ ] Tempo trace JSON fetched and saved (if trace_id captured)
- [ ] Row semantics match current proof runbook
- [ ] Only then fold into canonical EVIDENCE.md
`;

writeFileSync(join(outDir, 'EVIDENCE.md'), md);

console.log(JSON.stringify({ runDir: outDir, outcome: verdict, rowId: args.row, candidateOnly: true }, null, 2));
