/**
 * Post-processor: transforms k6 evidence JSON into PROOFS/<SHA>/<ROW>/ artifacts.
 *
 * Usage:
 *   node post-process/evidence-writer.js <k6-output.json> <row-id> <seat-name> <sha>
 *
 * Writes:
 *   PROOFS/<sha>/<row>/<seat>/
 *     ├── EVIDENCE.md
 *     ├── k6-summary.json
 *     └── gateway-events.ndjson
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';

const [,, inputFile, rowId, seatName, sha] = process.argv;

if (!inputFile || !rowId || !seatName || !sha) {
  console.error('Usage: node evidence-writer.js <k6-output.json> <row-id> <seat-name> <sha>');
  process.exit(1);
}

const raw = readFileSync(inputFile, 'utf-8');

// Extract the evidence JSON block from k6 console output
const evidenceMatch = raw.match(/--- .* EVIDENCE SUMMARY ---\n([\s\S]*?)\n--- END EVIDENCE ---/);
if (!evidenceMatch) {
  console.error('Could not find evidence summary block in k6 output');
  process.exit(1);
}

const evidence = JSON.parse(evidenceMatch[1]);

// Build output directory
const outDir = join('PROOFS', sha, rowId, seatName);
mkdirSync(outDir, { recursive: true });

// Write k6-summary.json
writeFileSync(join(outDir, 'k6-summary.json'), JSON.stringify(evidence, null, 2));

// Write gateway-events.ndjson
if (evidence.events && evidence.events.length > 0) {
  const ndjson = evidence.events.map((e) => JSON.stringify(e)).join('\n') + '\n';
  writeFileSync(join(outDir, 'gateway-events.ndjson'), ndjson);
}

// Generate EVIDENCE.md
const verdict = evidence.tool_accepted || evidence.prompt_sent
  ? (evidence.child_spawned || evidence.task_created ? 'PASS-CANDIDATE' : 'PARTIAL')
  : 'FAIL-CANDIDATE';

const md = `# ${rowId} — k6 Proof Evidence

## Verdict: ${verdict}

**Seat:** ${seatName}
**SHA:** ${sha}
**Nonce:** ${evidence.nonce}
**Started:** ${evidence.started}
**Ended:** ${evidence.ended}
**Duration:** ${evidence.duration_ms}ms

## Receipts

| Check | Result |
|-------|--------|
| Tool/prompt accepted | ${evidence.tool_accepted || evidence.prompt_sent ? '✓' : '✗'} |
| Task/child created | ${evidence.task_created || evidence.child_spawned ? '✓' : '✗'} |
| Parent return observed | ${evidence.parent_return ? '✓' : '✗'} |
| Bracket observed | ${evidence.bracket_observed !== undefined ? (evidence.bracket_observed ? '✓' : '✗ (honest-limit expected for message-body delivery)') : 'N/A'} |

## Notes

- Generated by k6-proof-harness post-processor.
- Raw events: see \`gateway-events.ndjson\` (${evidence.events ? evidence.events.length : 0} frames captured).
- Human review required before promotion to PASS.

## Artifacts

- \`k6-summary.json\` — structured evidence
- \`gateway-events.ndjson\` — raw gateway WS frames
`;

writeFileSync(join(outDir, 'EVIDENCE.md'), md);

console.log(`✓ Evidence written to ${outDir}/`);
console.log(`  Verdict: ${verdict}`);
console.log(`  Events: ${evidence.events ? evidence.events.length : 0}`);
`;
