import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm, readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { spawnSync } from 'node:child_process';

const repoRoot = new URL('../../../..', import.meta.url).pathname;
const script = join(repoRoot, 'tools/k6-proofs/scripts/postprocess-k6-summary.mjs');
const manifest = join(repoRoot, 'tools/k6-proofs/manifests/preflight.example.json');
const summary = join(repoRoot, 'tools/k6-proofs/examples/k6-summary.preflight.example.json');
const staticManifests = [
  join(repoRoot, 'tools/k6-proofs/manifests/r-cw-5a-static.json'),
  join(repoRoot, 'tools/k6-proofs/manifests/r-cw-6a-static.json'),
];

async function withTmp(fn) {
  const dir = await mkdtemp(join(tmpdir(), 'p81-k6-golden-'));
  try {
    return await fn(dir);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
}

function runPostprocess(args) {
  return spawnSync(process.execPath, [script, ...args], {
    cwd: repoRoot,
    encoding: 'utf8',
  });
}

test('offline preflight summary writes candidate golden-path artifacts', async () => {
  await withTmp(async (outRoot) => {
    const run = runPostprocess([
      '--manifest', manifest,
      '--summary', summary,
      '--out-root', outRoot,
      '--run-id', 'k6-run-golden-path-test',
    ]);

    assert.equal(run.status, 0, run.stderr || run.stdout);
    const printed = JSON.parse(run.stdout);
    assert.equal(printed.outcome, 'PASS-candidate');
    assert.equal(printed.candidateOnly, true);

    const resultPath = join(printed.runDir, 'row-result.json');
    const evidencePath = join(printed.runDir, 'EVIDENCE.md');

    for (const name of ['row-manifest.json', 'k6-summary.json', 'row-result.json', 'EVIDENCE.md']) {
      assert.equal(existsSync(join(printed.runDir, name)), true, `${name} missing`);
    }

    const result = JSON.parse(await readFile(resultPath, 'utf8'));
    assert.equal(result.schema, 'openclaw.k6.proof-row-result.v1');
    assert.equal(result.outcome, 'PASS-candidate');
    assert.equal(result.candidateOnly, true);
    assert.equal(result.foldRequiresReview, true);

    const evidence = await readFile(evidencePath, 'utf8');
    assert.match(evidence, /Generated by `tools\/k6-proofs\/scripts\/postprocess-k6-summary\.mjs`/);
    assert.match(evidence, /candidate output/);
  });
});

test('postprocessor rejects manifests that do not declare candidateOnly', async () => {
  await withTmp(async (outRoot) => {
    const badManifest = join(outRoot, 'bad-manifest.json');
    const parsed = JSON.parse(await readFile(manifest, 'utf8'));
    parsed.review.candidateOnly = false;
    await writeFile(badManifest, `${JSON.stringify(parsed, null, 2)}\n`);

    const run = runPostprocess([
      '--manifest', badManifest,
      '--summary', summary,
      '--out-root', outRoot,
      '--run-id', 'k6-run-should-not-write',
    ]);

    assert.notEqual(run.status, 0, 'postprocessor unexpectedly accepted candidateOnly=false');
    assert.match(run.stderr, /candidateOnly=true/);
  });
});

test('construct-only R-CW static rows never become PASS-candidate artifacts', async () => {
  await withTmp(async (outRoot) => {
    for (const staticManifest of staticManifests) {
      const run = runPostprocess([
        '--manifest', staticManifest,
        '--summary', summary,
        '--out-root', outRoot,
        '--run-id', `k6-run-${staticManifest.includes('5a-') ? '5a' : '6a'}-construct-only`,
      ]);

      assert.equal(run.status, 0, run.stderr || run.stdout);
      const printed = JSON.parse(run.stdout);
      assert.equal(printed.outcome, 'construct-only');
      const result = JSON.parse(await readFile(join(printed.runDir, 'row-result.json'), 'utf8'));
      assert.equal(result.outcome, 'construct-only');
      assert.equal(result.liveRunSafety.expectedArtifactClass, 'construct-only');
      assert.match(result.reason, /not behavioral candidate evidence/);
    }
  });
});
